### ISSUE TITLE
Emrald wallet loop at start

### ISSUE THREAD

**Issue by premiero** [ETCDEVTeam/emerald-wallet#434]
When i first launched wallet it asked me RPC type (remote or local); I took full local node), than in step 3 it showed me green button OPEN WALLET. Whenn I click "Open Wallet" it says:
1. Local Geth RPC API is ready
2. Launching geth backend
and then it get back to step 3 (Open Wallet)
I can click it over and over again, and it always get back to Open Wallet screen.
I have fully synced blockchain.
Please help it is very annoying, i do not have acces to my ETC, because old "core" client is not working anymore since "Gotham". I have my keystore, but can't import to emrald wallet because it won't open.

**Comment by gagarin55** [comment]
Could you please provide emerald logs, you can find it here:


    OSX: ~/Library/Logs/EmeraldWallet/log.log

    Linux: ~/.config/EmeraldWallet/log.log

**Comment by premiero** [comment]
Actually it is  win-v0.7.0 app. Which log would u like?

**Comment by premiero** [comment]
`[2018-01-11 21:42:23.410] [info] userData:  C:\Users\Łukasz\AppData\Roaming\EmeraldWallet
[2018-01-11 21:42:23.413] [info] Chain: {"client":"Geth/v4.0.0/windows/go1.8","id":61,"name":"mainnet"}
[2018-01-11 21:42:23.414] [info] Settings:  { version: 1,
  geth: { url: 'http://127.0.0.1:8545', type: 'local' },
  chain: { client: 'Geth/v4.0.0/windows/go1.8', id: 61, name: 'mainnet' },
  terms: 'v1' }
[2018-01-11 21:42:23.432] [info] Starting Emerald...
[2018-01-11 21:42:23.485] [info] Run services from C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources
[2018-01-11 21:42:23.486] [debug] New Services setup { connector: { launchType: 1, url: 'http://127.0.0.1:1920' },
  geth: { url: 'http://127.0.0.1:8545', type: 'local', launchType: 4 },
  chain: { client: 'Geth/v4.0.0/windows/go1.8', id: 61, name: 'mainnet' } }
[2018-01-11 21:42:23.500] [info] Starting Emerald Connector...
[2018-01-11 21:42:23.500] [debug] Checking if emerald exists: C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources\emerald.exe
[2018-01-11 21:42:23.506] [debug] OK: emerald exists:  C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources\emerald.exe
[2018-01-11 21:42:23.507] [debug] Emerald bin: C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources\emerald.exe, args: import,--chain=mainnet,--all,C:\Users\Łukasz/.emerald/mainnet/keystore/
[2018-01-11 21:42:23.751] [debug] Emerald execution status: 1
[2018-01-11 21:42:23.784] [debug] Emerald bin: C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources\emerald.exe, args: server
[2018-01-11 21:42:23.973] [debug] Emerald log target dir: C:\Users\Łukasz\AppData\Roaming\EmeraldWallet\logs
[2018-01-11 21:42:24.006] [debug] [emerald] [ERROR]	Command execution error: KeyFile storage error: Can't create database Keyfile storage

[2018-01-11 21:42:24.009] [error] Emerald Connector process exited with code: 1
[2018-01-11 21:42:24.505] [error] FetchError: request to http://localhost:8545 failed, reason: connect ECONNREFUSED 127.0.0.1:8545
    at ClientRequest.<anonymous> (C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources\app.asar\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[2018-01-11 21:42:24.506] [info] Can't find existing RPC. Try to launch
[2018-01-11 21:42:24.507] [debug] geth.exe exists
[2018-01-11 21:42:24.507] [info] Starting Geth... [bin: C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources network: mainnet, port: 8545]
[2018-01-11 21:42:24.508] [debug] Geth options: [--chain,mainnet,--rpc,--rpc-port,8545,--rpc-cors-domain,http://localhost:8000,--cache=128,--fast,--log-dir,C:\Users\Łukasz\AppData\Roaming\EmeraldWallet\logs\geth]
[2018-01-11 21:42:24.841] [info] index - Starting Emerald Wallet...
[2018-01-11 21:42:24.887] [debug] screen - Show screen:  null
[2018-01-11 21:42:24.926] [debug] launcherActions - Got launcher config from electron: {"version":1,"geth":{"url":"http://127.0.0.1:8545","type":"local"},"chain":{"client":"Geth/v4.0.0/windows/go1.8","id":61,"name":"mainnet"},"terms":"v1"}
[2018-01-11 21:42:24.945] [debug] launcherActions - Running launcher listener
[2018-01-11 21:42:24.948] [debug] screen - Show screen:  welcome
[2018-01-11 21:42:25.012] [debug] launcherActions - launcher listener:  type MESSAGE message { level: 2, msg: 'Launching Geth backend' }
[2018-01-11 21:42:25.556] [info] RPC is ready: Geth/v4.0.0/windows/go1.8
[2018-01-11 21:42:25.557] [debug] launcherActions - launcher listener:  type MESSAGE message { level: 2, msg: 'Local Geth RPC API is ready' }
[2018-01-11 21:42:25.560] [debug] launcherActions - launcher listener:  type CHAIN message { chain: 'mainnet', chainId: 61 }
[2018-01-11 21:42:25.562] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: { status: 'ready', type: 'local', url: 'http://127.0.0.1:8545' },
  service: 'geth' }
[2018-01-11 21:42:26.776] [debug] on get-status
[2018-01-11 21:42:26.778] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: { status: 'not ready', url: 'http://127.0.0.1:1920' },
  service: 'connector' }
[2018-01-11 21:42:26.781] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: { status: 'ready', type: 'local', url: 'http://127.0.0.1:8545' },
  service: 'geth' }
[2018-01-11 21:42:27.709] [info] launcherActions - Save settings { chain: { client: 'Geth/v4.0.0/windows/go1.8', id: 61, name: 'mainnet' },
  geth: { status: 'ready', type: 'local', url: 'http://127.0.0.1:8545' } }
[2018-01-11 21:42:27.710] [info] Update settings { chain: { client: 'Geth/v4.0.0/windows/go1.8', id: 61, name: 'mainnet' },
  geth: { status: 'ready', type: 'local', url: 'http://127.0.0.1:8545' } }
[2018-01-11 21:42:27.725] [info] Shutting down Local Geth
[2018-01-11 21:42:27.725] [info] Shutting down Local Connector
[2018-01-11 21:42:27.726] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: { status: 'not ready', url: 'http://127.0.0.1:1920' },
  service: 'connector' }
[2018-01-11 21:42:27.775] [error] geth process exited with code: null
[2018-01-11 21:42:27.776] [debug] New Services setup { connector: { launchType: 1, url: 'http://127.0.0.1:1920' },
  geth: { url: 'http://127.0.0.1:8545', type: 'local', launchType: 4 },
  chain: { client: 'Geth/v4.0.0/windows/go1.8', id: 61, name: 'mainnet' } }
[2018-01-11 21:42:27.777] [info] Starting Emerald Connector...
[2018-01-11 21:42:27.777] [debug] Checking if emerald exists: C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources\emerald.exe
[2018-01-11 21:42:27.777] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: 
   { status: 'not ready',
     type: 'local',
     url: 'http://127.0.0.1:8545' },
  service: 'geth' }
[2018-01-11 21:42:27.777] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: { status: 'not ready', url: 'http://127.0.0.1:1920' },
  service: 'connector' }
[2018-01-11 21:42:27.778] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: 
   { status: 'not ready',
     type: 'local',
     url: 'http://127.0.0.1:8545' },
  service: 'geth' }
[2018-01-11 21:42:27.778] [debug] OK: emerald exists:  C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources\emerald.exe
[2018-01-11 21:42:27.778] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: 
   { status: 'not ready',
     type: 'local',
     url: 'http://127.0.0.1:8545' },
  service: 'geth' }
[2018-01-11 21:42:27.779] [debug] Emerald bin: C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources\emerald.exe, args: import,--chain=mainnet,--all,C:\Users\Łukasz/.emerald/mainnet/keystore/
[2018-01-11 21:42:27.996] [debug] Emerald execution status: 1
[2018-01-11 21:42:27.997] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: { status: 'not ready', url: 'http://127.0.0.1:1920' },
  service: 'connector' }
[2018-01-11 21:42:27.997] [debug] Emerald bin: C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources\emerald.exe, args: server
[2018-01-11 21:42:28.187] [debug] Emerald log target dir: C:\Users\Łukasz\AppData\Roaming\EmeraldWallet\logs
[2018-01-11 21:42:28.216] [debug] [emerald] [ERROR]	Command execution error: KeyFile storage error: Can't create database Keyfile storage

[2018-01-11 21:42:28.219] [error] Emerald Connector process exited with code: 1
[2018-01-11 21:42:28.780] [error] FetchError: request to http://localhost:8545 failed, reason: connect ECONNREFUSED 127.0.0.1:8545
    at ClientRequest.<anonymous> (C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources\app.asar\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1283:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

[2018-01-11 21:42:28.780] [info] Can't find existing RPC. Try to launch
[2018-01-11 21:42:28.782] [debug] geth.exe exists
[2018-01-11 21:42:28.782] [info] Starting Geth... [bin: C:\Users\Łukasz\AppData\Local\Programs\EmeraldWallet\resources network: mainnet, port: 8545]
[2018-01-11 21:42:28.784] [debug] Geth options: [--chain,mainnet,--rpc,--rpc-port,8545,--rpc-cors-domain,http://localhost:8000,--cache=128,--fast,--log-dir,C:\Users\Łukasz\AppData\Roaming\EmeraldWallet\logs\geth]
[2018-01-11 21:42:28.847] [debug] launcherActions - launcher listener:  type MESSAGE message { level: 2, msg: 'Launching Geth backend' }
[2018-01-11 21:42:29.352] [info] RPC is ready: Geth/v4.0.0/windows/go1.8
[2018-01-11 21:42:29.353] [debug] launcherActions - launcher listener:  type MESSAGE message { level: 2, msg: 'Local Geth RPC API is ready' }
[2018-01-11 21:42:29.363] [debug] launcherActions - launcher listener:  type CHAIN message { chain: 'mainnet', chainId: 61 }
[2018-01-11 21:42:29.370] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: { status: 'ready', type: 'local', url: 'http://127.0.0.1:8545' },
  service: 'geth' }
[2018-01-11 21:42:29.727] [debug] on get-status
[2018-01-11 21:42:29.728] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: { status: 'not ready', url: 'http://127.0.0.1:1920' },
  service: 'connector' }
[2018-01-11 21:42:29.729] [debug] launcherActions - launcher listener:  type SERVICE_STATUS message { mode: { status: 'ready', type: 'local', url: 'http://127.0.0.1:8545' },
  service: 'geth' }
[2018-01-11 21:42:30.094] [info] Shutting down Local Geth
[2018-01-11 21:42:30.094] [info] Shutting down Local Connector
`

**Comment by premiero** [comment]
Is it possible, it is because Polish diacritic signs in my profle folder name (ie.: C:\Users\**Łukasz**\ ...)?

**Comment by gagarin55** [comment]
Thank, will check it

**Comment by premiero** [comment]
I can confirm it is a bug. I tried it at 2 different PC with differnt OS-es (Windows 7 and Windows 10) and when running as user **Łukasz** - impossible to open wallet.
So I created account name **Lukasz** and voila - everything works.

**Comment by BelfordZ** [comment]
Same issue on OSX:
![routermessed](https://user-images.githubusercontent.com/1787231/35286586-445bc604-0015-11e8-9cbe-3b712e1dc80c.gif)

console logs:
![image](https://user-images.githubusercontent.com/1787231/35286613-55686182-0015-11e8-9b89-20b60abace71.png)

emerald logs: https://pastebin.com/1Q9r5At1

**Comment by gagarin55** [comment]
Yes, the problem with non-latin latters in the path, there is no fix at the moment for rocksdb implementation.

**Comment by premiero** [comment]
Why it is closed? Is it fixed?
