### ISSUE TITLE
http://mewapi.epool.io/

### ISSUE THREAD

**Issue by zunnamu** [ETCDEVTeam/emerald-wallet#495]
[http://mewapi.epool.io/](url)
what can i do? when do you fix this site?

**Comment by gagarin55** [comment]
Whats the problem with it ?

**Comment by h3110w0r1d** [comment]
[2018-03-10 23:59:41.436] [error] Failed to start Services: FetchError: invalid json response body at https://mewapi.epool.io reason: Unexpected end of JSON input
    at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
