### ISSUE TITLE
https://mewapi.epool.io  does not work for http post method

### ISSUE THREAD

**Issue by h3110w0r1d** [ETCDEVTeam/emerald-wallet#521]
[2018-03-10 23:59:41.436] [error] Failed to start Services: FetchError: invalid json response body at https://mewapi.epool.io reason: Unexpected end of JSON input
at /Applications/EmeraldWallet.app/Contents/Resources/app.asar/node_modules/node-fetch/lib/body.js:48:31
at 
at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by h3110w0r1d** [comment]
post method:
500 Internal Server Error
openresty/1.13.6.1

get method:
Used HTTP Method is not allowed. POST or OPTIONS is required

please fix the api,i need to signin.thanks.

**Comment by mrpyle** [comment]
Same issue here. Stuck on starting screen, console shows the same error.
