### ISSUE TITLE
Invalid hex string on tx sign

### ISSUE THREAD

**Issue by splix** [ETCDEVTeam/emerald-wallet#632]
Can't send a transaction, receive "Invalid hex string" dialog after entering a passwrod and clicking  _Sign_

```
[16:40:29.455] screenActions - Show error TypeError: Invalid hex string
    at Buffer.write (buffer.js:768:21)
    at fromString (buffer.js:212:18)
    at Function.Buffer.from (buffer.js:104:12)
    at new Buffer (buffer.js:85:17)
    at Object.intToBuffer (file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:108069:10)
    at Object.exports.toBuffer (file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:20044:19)
    at Transaction.setter [as r] (file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:20518:19)
    at Transaction.hash (file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:42499:16)
    at Transaction.verifySignature (file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:42557:24)
    at file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:76856:14
```

**Comment by BelfordZ** [comment]
Im unable to reproduce this using mainnet. What network configuration where you using?

**Comment by splix** [comment]
morden remote gastracker

**Comment by splix** [comment]
build EmeraldWallet-mac-v0.10.0+51-43dc2a9

**Comment by BelfordZ** [comment]
Should be fixed as a result of the createtx refactoring that took place in https://github.com/ETCDEVTeam/emerald-wallet/pull/638
