### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by SamuraiXa** [ETCDEVTeam/emerald-wallet#710]
``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Michael/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23949:30)
    at new JsonRpcError (file:///C:/Users/Michael/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23978:116)
    at file:///C:/Users/Michael/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24015:19
    at <anonymous>
 ```

**Comment by BelfordZ** [comment]
We need to properly display this error as 'insufficient gas'

**Comment by shanejonas** [comment]
`insufficient funds` sounds like the proper name for the error

**Comment by splix** [comment]
It happens when you try to send "Max" amount, the wallet incorrectly calculates values to send

**Comment by splix** [comment]
rel #750

**Comment by splix** [comment]
dup #828
