### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by sathebm** [ETCDEVTeam/emerald-wallet#747]
``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/sathe/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23949:30)
    at new JsonRpcError (file:///C:/Users/sathe/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23978:116)
    at file:///C:/Users/sathe/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24015:19
    at <anonymous>
 ```

**Comment by BelfordZ** [comment]
duplicate of #750
