### ISSUE TITLE
Cannot read property 'timestamp' of undefined

### ISSUE THREAD

**Issue by ghost** [ETCDEVTeam/emerald-wallet#754]
``` 
TypeError: Cannot read property 'timestamp' of undefined
    at file:///home/master/workplace/emerald-wallet/app/index.js:73466:13
    at Array.map (native)
    at file:///home/master/workplace/emerald-wallet/app/index.js:73461:28
    at <anonymous>
 ```

**Comment by BelfordZ** [comment]
will be fixed shortly -- thanks for trying out master :) :)
