### ISSUE TITLE
Invalid data format: Invalid passphrase

### ISSUE THREAD

**Issue by killit93** [ETCDEVTeam/emerald-wallet#783]
cant send password not working.

``` 
JsonRpcError: Invalid data format: Invalid passphrase
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/James/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23949:30)
    at new JsonRpcError (file:///C:/Users/James/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:23978:116)
    at file:///C:/Users/James/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24015:19
    at <anonymous>
 ```

**Comment by BelfordZ** [comment]
This is an bug with the current release that gives a terrible error for when you put in your password wrong.

Make sure you have the right password.

**Comment by cryptochiefy** [comment]
So what if we lost our password but have a backup password?

**Comment by cryptochiefy** [comment]
@splix Nah im stupid and realised you need ETC to cover the gas limit costs i think. I thought my token i was trying to send would cover it but it kept saying invalid balance.

**Comment by splix** [comment]
Ah, yeah, you need ether to send tokens. We need to give some message for that case

**Comment by cryptochiefy** [comment]
Yeah that would be nice but i managed to figure it out haha :+1:
