### ISSUE TITLE
addresses.map(...).toJS is not a function

### ISSUE THREAD

**Issue by tzdybal** [ETCDEVTeam/emerald-wallet#789]
``` 
TypeError: addresses.map(...).toJS is not a function
    at file:///C:/Program%20Files/EmeraldWallet/resources/app.asar/app/index.js:72077:8
    at file:///C:/Program%20Files/EmeraldWallet/resources/app.asar/app/index.js:197791:18
    at file:///C:/Program%20Files/EmeraldWallet/resources/app.asar/app/index.js:71965:23
    at dispatch (file:///C:/Program%20Files/EmeraldWallet/resources/app.asar/app/index.js:197846:18)
    at file:///C:/Program%20Files/EmeraldWallet/resources/app.asar/app/index.js:72457:7
    at <anonymous>
 ```

**Comment by BelfordZ** [comment]
Should be fixed now. Give it a try!
