### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R

### ISSUE THREAD

**Issue by ihorzenich** [ETCDEVTeam/emerald-wallet#808]
``` 
JsonRpcError: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R
    at JsonRpcError.ExtendableBuiltin (file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:23949:30)
    at new JsonRpcError (file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:23978:116)
    at file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:24015:19
    at <anonymous>
 ```

**Comment by splix** [comment]
dup #863
