### ISSUE TITLE
Invalid data format: Wallet addr:0xf9dc50ee081460f5b0cfb16580b3d7ec5a4c89e

### ISSUE THREAD

**Issue by splix** [ETCDEVTeam/emerald-wallet#843]
```
JsonRpcError: Invalid data format: 
Wallet addr:0xf9dc50ee081460f5b0cfb16580b3d7ec5a4c89e on path:USB_2c97_0001_14110000, can't sign transaction: HD Wallet error: Failed to retrieve error message
    at JsonRpcError.ExtendableBuiltin (file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:24080:30)
    at new JsonRpcError (file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:24109:116)
    at file:///Applications/EmeraldWallet.app/Contents/Resources/app.asar/app/index.js:24146:19
```

**Comment by splix** [comment]
Notice that address string is 41 character length (i.e. 39 for addr)

**Comment by BelfordZ** [comment]
Is this while  sending HW wallet tx?

**Comment by splix** [comment]
yes
