### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by tzdybal** [ETCDEVTeam/emerald-wallet#846]
I tried to send a transaction after clicking on "MAX" Amount.

``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///home/tomek/opt/EmeraldWallet-linux-x64-v1.1.0+4-e682346/resources/app.asar/app/index.js:24080:30)
    at new JsonRpcError (file:///home/tomek/opt/EmeraldWallet-linux-x64-v1.1.0+4-e682346/resources/app.asar/app/index.js:24109:116)
    at file:///home/tomek/opt/EmeraldWallet-linux-x64-v1.1.0+4-e682346/resources/app.asar/app/index.js:24146:19
 ```

**Comment by BelfordZ** [comment]
Dupe of #761
