### ISSUE TITLE
Invalid data format: Invalid passphrase

### ISSUE THREAD

**Issue by rocky3xr** [ETCDEVTeam/emerald-wallet#861]
I've never set a passphrase for this wallet

``` 
JsonRpcError: Invalid data format: Invalid passphrase
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/roque/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24080:30)
    at new JsonRpcError (file:///C:/Users/roque/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24109:116)
    at file:///C:/Users/roque/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24146:19
 ```

**Comment by rocky3xr** [comment]
How's possible the wallet ask me to put the password and sign before sending, when I've never been asked for encrypting the wallet?

**Comment by gagarin55** [comment]
When user creates new account by importing/generate EmeraldWallet asks him set passphrase.
How did you create that account ?
