### ISSUE TITLE
rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R

### ISSUE THREAD

**Issue by GFleming** [ETCDEVTeam/emerald-wallet#863]
Unable to create transaction.

``` 
JsonRpcError: rlp: non-canonical integer (leading zero bytes) for *big.Int, decoding into (types.Transaction)(types.txdata).R
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Administrator/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24080:30)
    at new JsonRpcError (file:///C:/Users/Administrator/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24109:116)
    at file:///C:/Users/Administrator/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24146:19
 ```

**Comment by splix** [comment]
Fixed in [fd58ac3], will be available since v1.3.3
