### ISSUE TITLE
Gateway timeout

### ISSUE THREAD

**Issue by xussain** [ETCDEVTeam/emerald-wallet#864]
``` 
JsonRpcError: Gateway timeout
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/i/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24080:30)
    at new JsonRpcError (file:///C:/Users/i/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24109:116)
    at file:///C:/Users/i/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24146:19
 ```

**Comment by splix** [comment]
rel #835
