### ISSUE TITLE
cannot launch geth backend win-v1.1.1+24-2b96c8a

### ISSUE THREAD

**Issue by teknowill** [ETCDEVTeam/emerald-wallet#866]
I've tried uninstalling and reinstalling, reboots, no luck in win-v1.1.1+24-2b96c8a, was working for while now it won't
in the console you can see a lot of errors, not sure what to do
index.js:21605 Warning: Received `true` for a non-boolean attribute `secondary`.

If you want to write it to the DOM, pass a string instead: secondary="true" or secondary={value.toString()}.
    in div (created by CircularProgress)
    in CircularProgress (created by Screen)
    in div (created by Screen)
    in Screen (created by Connect(Screen))
    in Connect(Screen)
    in div
    in div
    in Unknown (created by I18n)
    in I18n (created by Translate(Component))
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by MuiComponent)
    in MuiComponent (created by App)
    in MuiThemeProvider (created by App)
    in Provider (created by App)
    in I18nextProvider (created by App)
    in App
printWarning @ index.js:21605
----
13:57:10.255] FetchError: request to http://localhost:8545 failed, reason: connect ECONNREFUSED 127.0.0.1:8545
    at ClientRequest.<anonymous> (C:\Users\test\AppData\Local\Programs\EmeraldWallet\resources\app.asar\node_modules\isomorphic-fetch\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

(anonymous) @ index.js:76552
---
[13:57:14.023] geth process exited with code: 1
(anonymous) @ index.js:76552

**Comment by teknowill** [comment]
C:\Users\test>C:\Users\test\AppData\Local\Programs\EmeraldWallet\resources\geth.exe
2018-12-22 14:07:11 Geth Classic version: v5.5.1-8a3bc2d
2018-12-22 14:07:11 Blockchain: Ethereum Classic Mainnet
2018-12-22 14:07:11 Chain database: C:\Users\test\AppData\Roaming\EthereumClassic\mainnet/chaindata
2018-12-22 14:07:11 Blockchain upgrades configured: 6
2018-12-22 14:07:11  1150000 Homestead
2018-12-22 14:07:11  1920000 The DAO Hard Fork (0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f)
2018-12-22 14:07:11  2500000 GasReprice
2018-12-22 14:07:11  3000000 Diehard
2018-12-22 14:07:11  5000000 Gotham
2018-12-22 14:07:11  5900000 Defuse Difficulty Bomb
2018-12-22 14:07:11 Using 10 configured bootnodes
2018-12-22 14:07:11 Use Sputnik EVM: false
2018-12-22 14:07:11 No etherbase set and no accounts found as default
2018-12-22 14:07:11 Allotted 1024MB cache and 1024 file handles to C:\Users\test\AppData\Roaming\EthereumClassic\mainnet\chaindata
2018-12-22 14:07:12 Allotted 16MB cache and 16 file handles to C:\Users\test\AppData\Roaming\EthereumClassic\mainnet\dapp
2018-12-22 14:07:12 Protocol Versions: [63 62], Network Id: 1, Chain Id: 61
Fatal: Error starting protocol stack: leveldb/table: corruption on data-block (pos=1651837): checksum mismatch, want=0xa1dc49b1 got=0x413683fe [file=1971094.ldb]

**Comment by teknowill** [comment]
tried removing chaindata 2032025, to maybe force a recovery, not sure if working, but I think geth is running/working on it based on log
[LOG-old.zip](https://github.com/ETCDEVTeam/emerald-wallet/files/2705479/LOG-old.zip)
, but not sure. seems like errors can happen if your computer frezzes or something and end up in a loop
[LOG.zip](https://github.com/ETCDEVTeam/emerald-wallet/files/2705478/LOG.zip)

**Comment by teknowill** [comment]
that got it running again, but 1971904 is still missing, not sure what the impact of that will be

**Comment by teknowill** [comment]
seems to be resyncing:: You are connected to not synced node, your balances can show wrong value.
About 15918 blocks left. but if possible adding some kind of bad block/ldb file detection and removal might help less technical people recovery their wallets after a system freeze.  

=============== Dec 22, 2018 (EST) ===============
14:35:04.289421 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
14:35:04.437945 version@stat F·[38424] S·69GiB[69GiB] Sc·[9606.00]
14:35:04.443947 db@open opening
14:35:04.589471 journal@recovery F·1
14:35:04.596472 journal@recovery recovering @2032063
14:35:04.666485 memdb@flush created L0@2032064 N·21252 S·1MiB "\x00\x00\xae..\x82\x88\x11,v352740225":"\xff\xfc\x94..\xa5\x05\xa1,v352742289"
14:35:04.678488 version@stat F·[38425] S·69GiB[69GiB] Sc·[9606.25]
14:35:04.870520 db@janitor F·38428 G·1
14:35:04.870520 db@janitor removing manifest-2032063
14:35:04.872020 db@open done T·428.0735ms
14:35:04.896525 table@compaction L0·38425 -> L1·0 S·69GiB Q·352744658
14:36:19.133479 table@build created L1@2032067 N·7782 S·2MiB "\x00\x00\x00..\x18\x96\x85,v346262217":"\x00\x02p..\x9b\xd9\xf5,v221707649"
14:36:30.271436 table@build created L1@2032068 N·7710 S·2MiB "\x00\x02p..\t;\x95,v40954718":"\x00\x04\xd7..G\xf0\xd0,v209327275"
14:36:41.394890 table@build created L1@2032069 N·7718 S·2MiB "\x00\x04\xd7..\x9f\x93t,v304747270":"\x00\aC..;ك,v231030083"
14:36:52.883412 table@build created L1@2032070 N·7812 S·2MiB "\x00\aC..\xf5\xccb,v329331875":"\x00\t\xbb..h\aK,v342556150"
14:37:04.141376 table@build created L1@2032071 N·7683 S·2MiB "\x00\t\xbb..qd\x1e,v240879233":"\x00\f\x1a..\n74,v252543475"
14:37:15.637928 table@build created L1@2032072 N·7791 S·2MiB "\x00\f\x1a..\xc1\xac\xf8,v301039557":"\x00\x0e\x88..\xe6z\x01,v33516077"
14:37:26.732885 table@build created L1@2032073 N·7733 S·2MiB "\x00\x0e\x88..\xefs\x0f,v321332279":"\x00\x10\xf7..\x9a&\xb9,v237665172"
14:37:38.110181 table@build created L1@2032074 N·7890 S·2MiB "\x00\x10\xf7..\x00ǳ,v265436474":"\x00\x13{..\x98K\x8a,v206720006"
14:37:50.108791 table@build created L1@2032075 N·7871 S·2MiB "\x00\x13{..\x1bI\x9b,v174490597":"\x00\x15\xec..\u007f\xe2&,v2357237"
14:38:01.453282 table@build created L1@2032076 N·7769 S·2MiB "\x00\x15\xec..a\xab\u007f,v262165007":"\x00\x18[..vj\xb3,v217382640"
14:38:13.021315 table@build created L1@2032077 N·7905 S·2MiB "\x00\x18[..j\xb3\x01,v217382641":"\x00\x1a\xd5..\a\u007f\xc8,v243349946"
14:38:24.142714 table@build created L1@2032078 N·7667 S·2MiB "\x00\x1a\xd5..\xd5]Y,v139333101":"\x00\x1d;..ꧨ,v124044124"
14:38:35.334619 table@build created L1@2032079 N·7706 S·2MiB "\x00\x1d;..\xa7\xa8\x01,v124044125":"\x00\x1f\xaa..g\xc2!,v77431619"
14:38:46.665111 table@build created L1@2032080 N·7774 S·2MiB "\x00\x1f\xaa..\xc2!\x01,v77431620":"\x00\"\x1f..\xa1Bl,v342383607"
14:38:58.307156 table@build created L1@2032081 N·7905 S·2MiB "\x00\"\x1f..z\xffs,v346997627":"\x00$\xa5..\xb9\x022,v236926117"
14:39:09.695157 table@build created L1@2032082 N·7844 S·2MiB "\x00$\xa5..\xe6k\x92,v346143849":"\x00'\x0e..ֳ\x05,v68096229"
14:39:20.749099 table@build created L1@2032083 N·7623 S·2MiB "\x00'\x0e..\xb3\x05\x01,v68096230":"\x00)\x88.._\x14%,v345267300"
14:39:31.932563 table@build created L1@2032084 N·7694 S·2MiB "\x00)\x88..\x8d0$,v218059859":"\x00+\xe8..\x14\x95\x01,v139344896"
14:39:43.298519 table@build created L1@2032085 N·7889 S·2MiB "\x00+\xe8..\xf2^\x96,v68814676":"\x00.d..J\xc8),v309338425"
14:39:54.516992 table@build created L1@2032086 N·7750 S·2MiB "\x00.d..\xa3^G,v352562782":"\x000\xce..\xaa\x8c\x86,v215690782"
14:40:05.628388 table@build created L1@2032087 N·7668 S·2MiB "\x000\xce..*\xe0\xf9,v266629761":"\x003>..[\xd7k,v25379961"
14:40:16.795826 table@build created L1@2032088 N·7676 S·2MiB "\x003>..\xd7k\x01,v25379962":"\x005\xa7..Wܱ,v224035328"
14:40:28.166332 table@build created L1@2032089 N·7823 S·2MiB "\x005\xa7..\xec\xfd\x14,v264804476":"\x008\x1e..ҏ\xcd,v245909047"
14:40:39.344797 table@build created L1@2032090 N·7643 S·2MiB "\x008\x1f..\xa8QX,v279797395":"\x00:\x85..K-d,v151210284"
14:40:50.599774 table@build created L1@2032091 N·7770 S·2MiB "\x00:\x85..-d\x01,v151210285":"\x00<\xff..\x16\xf8\x8c,v111527260"

**Comment by teknowill** [comment]
it's getting new blocks, so geth looks ok now, but the wallet keeps showing ever more block behind and won't show transactions past 12/18

  | printWarning | @ | index.js:21605
-- | -- | -- | --
  | warning | @ | index.js:21629
  | checkPropTypes | @ | index.js:33222
  | validatePropTypes | @ | index.js:189516
  | createElementWithValidation | @ | index.js:189613
  | MuiComponent | @ | index.js:660
  | mountIndeterminateComponent | @ | index.js:175223
  | beginWork | @ | index.js:175412
  | performUnitOfWork | @ | index.js:177415
  | workLoop | @ | index.js:177479
  | callCallback | @ | index.js:167733
  | invokeGuardedCallbackDev | @ | index.js:167772
  | invokeGuardedCallback | @ | index.js:167629
  | renderRoot | @ | index.js:177557
  | performWorkOnRoot | @ | index.js:178205
  | performWork | @ | index.js:178158
  | requestWork | @ | index.js:178069
  | scheduleWorkImpl | @ | index.js:177923
  | scheduleWork | @ | index.js:177880
  | enqueueSetState | @ | index.js:173403
  | Component.setState | @ | index.js:188582
  | onStateChange | @ | index.js:52569
  | notify | @ | index.js:187619
  | notifyNestedSubs | @ | index.js:187658
  | onStateChange | @ | index.js:52566
  | notify | @ | index.js:187619
  | notifyNestedSubs | @ | index.js:187658
  | onStateChange | @ | index.js:52566
  | dispatch | @ | index.js:53798
  | (anonymous) | @ | index.js:195387
  | (anonymous) | @ | index.js:195431
  | (anonymous) | @ | index.js:69804
  | (anonymous) | @ | index.js:34705
  | Promise.then (async) |   |  
  | startSync | @ | index.js:34704
  | Promise.then (async) |   |  
  | Object.defineProperty.value | @ | index.js:34792
  | __webpack_require__ | @ | index.js:20
  | Object.defineProperty.value | @ | index.js:68839
  | __webpack_require__ | @ | index.js:20
  | (anonymous) | @ | index.js:66
  | (anonymous) | @ | index.js:69

**Comment by teknowill** [comment]
Warning: Failed prop type: The prop `tokensBalances` is marked as required in `Account`, but its value is `undefined`.
    in Account (created by MuiComponent)
    in MuiComponent
    in div
    in div
    in Unknown (created by I18n)
    in I18n (created by Translate(Component))
    in Translate(Component) (created by MuiComponent)
    in MuiComponent (created by Connect(MuiComponent))
    in Connect(MuiComponent) (created by Dashboard)
    in div (created by Dashboard)
    in Dashboard (created by Connect(Dashboard))
    in Connect(Dashboard) (created by Screen)
    in Screen (created by Connect(Screen))
    in Connect(Screen)
    in div
    in div
    in Unknown (created by I18n)
    in I18n (created by Translate(Component))
    in Translate(Component) (created by Connect(Translate(Component)))
    in Connect(Translate(Component)) (created by MuiComponent)
    in MuiComponent (created by App)
    in MuiThemeProvider (created by App)
    in Provider (created by App)
    in I18nextProvider (created by App)

**Comment by teknowill** [comment]
ended up having to delete both EmeraldWallet and EthereumClassic for AppData\Roaming and resyncing from scratch
