### ISSUE TITLE
Invalid data format: Invalid passphrase

### ISSUE THREAD

**Issue by cryptochiefy** [ETCDEVTeam/emerald-wallet#891]
``` 
[etc.txt](https://github.com/ETCDEVTeam/emerald-wallet/files/2810680/etc.txt)

JsonRpcError: Invalid data format: Invalid passphrase
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/Mitchy/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24080:30)
    at new JsonRpcError (file:///C:/Users/Mitchy/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24109:116)
    at file:///C:/Users/Mitchy/AppData/Local/Programs/EmeraldWallet/resources/app.asar/app/index.js:24146:19
 ```

**Comment by developerkevin** [comment]
I have this same exact issue! Always thought I had forgotten my password but sometimes I don't use new passwords for each app, service, website and had also written it down to no success. A fairly good amount of ETC too. If this issue plagued two users, then there are likely more.
